trigger:
- main

pool:
  name: self-hosted  # 👈 or the name of the agent pool where your laptop is registered

steps:
- script: echo "👋 Hello, ProfitSense World!"
  displayName: "Say Hello from Local Agent"
