trigger:
- main

pool:
  name: Default  # 👈 or the name of the agent pool where your laptop is registered

steps:
- script: |
    cd C:\Users\Prasad\PycharmProjects\DE\ProfitSense
    python -m silver.silver_orderitems
  displayName: "Run Silver OrderItems via Module"

